"""added unique - true for teacher_id

Revision ID: 21646872a3d2
Revises: 993a12eb8c83
Create Date: 2025-04-12 11:57:51.471994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21646872a3d2'
down_revision = '993a12eb8c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['teacherId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
