"""added unique - true for leade_id in group

Revision ID: 24bd13b5ae5d
Revises: 93b36579ffcb
Create Date: 2025-04-11 22:33:34.277139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bd13b5ae5d'
down_revision = '93b36579ffcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['leader_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
