"""Initial migration

Revision ID: 2c1add5dc87e
Revises: 
Create Date: 2025-04-07 22:56:24.782017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1add5dc87e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examination_period',
    sa.Column('examination_period_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('EXAMEN', 'COLOCVIU', name='examtype'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('examination_period_id')
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SEC', 'SG', 'CD', 'ADM', name='userrole'), nullable=False),
    sa.Column('teacherId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('studyYear', sa.Integer(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('coordinator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coordinator_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('year_of_study', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('course_assistants',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('course_id', 'assistant_id')
    )
    op.create_table('exams',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('EXAMEN', 'COLOCVIU', name='examtype'), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('assistant_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('IN_ASTEPTARE', 'ACCEPTAT', 'RESPINS', name='examstatus'), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('exam_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exams')
    op.drop_table('course_assistants')
    op.drop_table('groups')
    op.drop_table('courses')
    op.drop_table('users')
    op.drop_table('rooms')
    op.drop_table('examination_period')
    # ### end Alembic commands ###
