"""chenge studyYear to study_year name into course

Revision ID: 7f7f856fa77f
Revises: cc7b308f07db
Create Date: 2025-04-09 16:46:12.024325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7f856fa77f'
down_revision = 'cc7b308f07db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_year', sa.Integer(), nullable=True))
        batch_op.drop_column('studyYear')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('studyYear', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('study_year')

    # ### end Alembic commands ###
