"""added examination method to course

Revision ID: 8cd8e0e77418
Revises: 2c1add5dc87e
Create Date: 2025-04-09 16:19:39.674242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd8e0e77418'
down_revision = '2c1add5dc87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('examinationMethod', sa.Enum('EXAMEN', 'COLOCVIU', name='examtype'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('examinationMethod')

    # ### end Alembic commands ###
