"""added start_time, duration and details to exam

Revision ID: 93b36579ffcb
Revises: d0cd8542e05c
Create Date: 2025-04-10 16:12:06.133905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b36579ffcb'
down_revision = 'd0cd8542e05c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('details', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('details')
        batch_op.drop_column('duration')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
