"""added unique - true for name in examination_period

Revision ID: 993a12eb8c83
Revises: 24bd13b5ae5d
Create Date: 2025-04-12 11:29:00.537430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993a12eb8c83'
down_revision = '24bd13b5ae5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examination_period', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examination_period', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
