"""chenge  examination method name  to course

Revision ID: cc7b308f07db
Revises: 8cd8e0e77418
Create Date: 2025-04-09 16:31:24.933195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc7b308f07db'
down_revision = '8cd8e0e77418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('examination_method', sa.Enum('EXAMEN', 'COLOCVIU', name='examtype'), nullable=True))
        batch_op.drop_column('examinationMethod')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('examinationMethod', postgresql.ENUM('EXAMEN', 'COLOCVIU', name='examtype'), autoincrement=False, nullable=True))
        batch_op.drop_column('examination_method')

    # ### end Alembic commands ###
